endpoints:
  hypermedia:
    enabled: true

management:
  context-path: /manage

server:
  error:
    whitelabel:
      enabled: false
  session:
    timeout: 600 # 10 minutes

spring:
  cache:
    jcache:
      config: ehcache.xml
  jpa:
    generate-ddl: true