spring:
  jpa:
    generate-ddl: true
  cache:
    jcache:
      config: ehcache.xml

server:
  error:
    whitelabel:
      enabled: false
  session:
    timeout: 600 # 10 minutes

management:
  context-path: /manage