INSERT INTO ACTIVITY VALUES('jyga', 'JYG Animator');
INSERT INTO ACTIVITY VALUES('jygp', 'JYG Participant');
INSERT INTO ACTIVITY VALUES('sct', 'SC Tutor');
INSERT INTO ACTIVITY VALUES('scp', 'SC Participant');
INSERT INTO ACTIVITY VALUES('dmh', 'DM Host');
INSERT INTO ACTIVITY VALUES('dmp', 'DM Participant');
INSERT INTO ACTIVITY VALUES('cct', 'CC Teacher');
INSERT INTO ACTIVITY VALUES('ccp', 'CC Participant');
INSERT INTO ACTIVITY VALUES('fh', 'Fireside Host');
INSERT INTO ACTIVITY VALUES('fp', 'Fireside Participant');

INSERT INTO COUNTRY VALUES('se');

INSERT INTO REGION VALUES('northern', '', 'se');
INSERT INTO REGION VALUES('central', '', 'se');
INSERT INTO REGION VALUES('southern', '', 'se');

INSERT INTO CLUSTER VALUES('stockholm', '', 'central');
INSERT INTO CLUSTER VALUES('uppsala', '', 'central');
INSERT INTO CLUSTER VALUES('skane', '', 'southern');

INSERT INTO TEAM VALUES(901, 262, 413.125, 'stockholm');
INSERT INTO TEAM VALUES(902, 189, 443.125, 'stockholm');
INSERT INTO TEAM VALUES(903, 58, 69, 'uppsala');

/* Hibernate generates columns in alphabetic order */
INSERT INTO MEMBER VALUES(111, 'John', 'Doe', 'M', 'I', 901);
INSERT INTO MEMBER VALUES(222, 'Jane', 'Die', 'O', 'II', 901);
INSERT INTO MEMBER VALUES(333, 'Michael', 'Rie', 'T', 'III', 902);
INSERT INTO MEMBER VALUES(444, 'Joss', 'Alright', '', '', 903);

INSERT INTO CAPABILITY VALUES(1, 'sct', 111);
INSERT INTO CAPABILITY VALUES(2, 'cct', 111);
INSERT INTO CAPABILITY VALUES(3, 'jyga', 111);
INSERT INTO CAPABILITY VALUES(4, 'dmh', 222);
INSERT INTO CAPABILITY VALUES(5, 'fh', 333);
INSERT INTO CAPABILITY VALUES(6, 'jyga', 333);

INSERT INTO COMMITMENT VALUES(12, 'sct', 111);
INSERT INTO COMMITMENT VALUES(13, 'dmh', 111);
INSERT INTO COMMITMENT VALUES(14, 'dmh', 222);
INSERT INTO COMMITMENT VALUES(15, 'fh', 333);
INSERT INTO COMMITMENT VALUES(16, 'jyga', 333);
INSERT INTO COMMITMENT VALUES(17, 'sct', 333);