INSERT INTO ACTIVITY VALUES('SC', 'Study Circle');
INSERT INTO ACTIVITY VALUES('DM', 'Devotional Meeting');
INSERT INTO ACTIVITY VALUES('JYG', 'Junior Youth Group');
INSERT INTO ACTIVITY VALUES('CC', 'Childrens class');
INSERT INTO ACTIVITY VALUES('HV', 'Home Visit');

INSERT INTO TEAM VALUES(901, 127, 138);
INSERT INTO TEAM VALUES(902, 58, 69);

/* Hibernate generates columns in alphabetic order */
INSERT INTO MEMBER VALUES(111, 'John', 'Doe', 'M', 'I', 901);
INSERT INTO MEMBER VALUES(222, 'Jane', 'Die', 'O', 'II', 901);
INSERT INTO MEMBER VALUES(333, 'Michael', 'Rie', 'T', 'III', 902);

INSERT INTO CAPABILITY VALUES(1, 'SC', 111);
INSERT INTO CAPABILITY VALUES(2, 'CC', 111);
INSERT INTO CAPABILITY VALUES(3, 'JYG', 111);
INSERT INTO CAPABILITY VALUES(4, 'DM', 222);
INSERT INTO CAPABILITY VALUES(5, 'HV', 333);
INSERT INTO CAPABILITY VALUES(6, 'JYG', 333);

INSERT INTO COMMITMENT VALUES(12, 'SC', 111);
INSERT INTO COMMITMENT VALUES(13, 'DM', 222);
INSERT INTO COMMITMENT VALUES(14, 'HV', 333);
INSERT INTO COMMITMENT VALUES(15, 'JYG', 333);

