endpoints:
  hypermedia:
    enabled: true

management:
  context-path: /manage
  security:
    roles: SUPER_ADMIN

server:
  error:
    whitelabel:
      enabled: false
  session:
    timeout: 600 # 10 minutes

spring:
  application:
    name: clusterview
  cache:
    jcache:
      config: ehcache.xml
  jpa:
    generate-ddl: true

springfox:
  documentation:
    swagger:
      v2:
        path: /manage/v2/api-docs